### ISSUE TITLE
MT00015: Realigning TMs that are Machine Aligned

### ISSUE THREAD

**Issue by TenzinGayche** [OpenPecha/mt-aligner-prep-tool#22]
### Description 
Realigning the TMs that are already aligned using the New alignment pipeline( BertAlign). 

### Completion Criteria 
New better aligned TMs that are aligned with the new alignment pipeline

- [x] write a script TM checker
- [x] Run the realigner script
- [x] Check if TMs are realigned properly
- [x] modify bo tokenizer script to handle large files
- [x] run again for ids with large files
- [x] understand the errors log
- [x] Run the merge realigner branch to main script

**Comment by tenzin3** [comment]
process being killed when tokenizing BO2383.txt (size = 35.2 MB),
For now, removed the id from the to_do.txt

**Comment by tenzin3** [comment]
Errors type

1. missing either BO or EN repo for id
2. No proper .txt file in BO or EN repo
3. Problem with aligner

**Comment by tenzin3** [comment]
1. missing either BO or EN repo for id
0230, 0272, 0414, 0415, 0416, 0669, 0671, 0673, 0672, 0674, 0676, 0677, 0678, 0680, 0681, 0682, 0679, 0683, 0684, 0685, 0687, 0686, 0688, 1209, 2207, 2323, 2729, 2756, 2757, 2760, 2763, 2761, 2770, 2781, 2783, 2786, 2785, 2788, 2791, 2800, 2801, 2811, 2819, 2812, 2824, 2869, 2879, 2933, 2935, 2945, 2999, 3013, 3029, 3031, 3030, 3034, 3037, 3038, 3046, 3045, 3047, 3049, 3052, 3071, 3062, 3053, 3072, 3137, 3138, 3139, 3210, 5R9G_LH, 6IZV_LH, 7142, 7584, 7769, 7727, 7789, 7884, 7796,

**Comment by tenzin3** [comment]
2.No proper .txt file in BO or EN repo
3842, 4130, 4909, 5006, 2941, 2724, 2176, 1987

**Comment by tenzin3** [comment]
3. Problem with aligner

7885, 2383, 2111, 2113, 3445, 2112, 2114, 2115

**Comment by tenzin3** [comment]
@TenzinGayche , above are the list of Ids facing problem when doing realigning, kindly talk with people related to this and notify me when its ready to be realign again. Thank you

**Comment by tenzin3** [comment]
Mismatch in tokenized output:>

text = "མངོན་སུམ་ཚད་མས་གྲུབ་པ་འདི་བཞིན་ནོ།།༄༅།།ཡུལ་སྐྱེ་རྒུ་མདོ་ན་མཆིས་པའི་བཙན་པོ་ཁྲི་ལྡེ་སྲོང་བཙན་སྐབས་བརྐོས་པའི་རྡོ་བརྐོས་ཡི་གེར་དཔྱད་པ།"
op_mt_tools tokenizer output ="མངོན་སུམ་ཚད་མས་གྲུབ་པ་འདི་བཞིན་ནོ།།༄༅།།ཡུལ་སྐྱེ་རྒུ་མདོ་ན་མཆིས་པའི་བཙན་པོ་ཁྲི་ལྡེ་སྲོང་བཙན་སྐབས་བརྐོས་པའི་རྡོ་བརྐོས་ཡི་གེར་དཔྱད་པ།\n"
new tokenizer output ="མངོན་སུམ་ཚད་མས་གྲུབ་པ་འདི་བཞིན་ནོ།།\n༄༅།།\nཡུལ་སྐྱེ་རྒུ་མདོ་ན་མཆིས་པའི་བཙན་པོ་ཁྲི་ལྡེ་སྲོང་བཙན་སྐབས་བརྐོས་པའི་རྡོ་བརྐོས་ཡི་གེར་དཔྱད་པ།\n"
